{
 "title": "KubeML",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jobs",
    "query": "label_values(kubeml_job_train_loss, jobid)"
   },
   {
    "name": "task",
    "query": "label_values(kubeml_job_running_total, type)"
   }
  ]
 },
 "panels": [
  { "title": "General View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Running Jobs",
   "type": "graph",
   "description": "Numbe of jobs currently running in the cluster, both of type inference and train",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubeml_job_running_total{type=~\"$task\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Train Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Validation Loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubeml_job_validation_loss{jobid=~\"$jobs\"}",
     "legendFormat": "{{jobid}}"
    }
   ]
  },
  {
   "title": "Train Loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubeml_job_train_loss{jobid=~\"$jobs\"}",
     "legendFormat": "{{jobid}}"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubeml_job_validation_accuracy{jobid=~\"$jobs\"}",
     "legendFormat": "{{jobid}}"
    }
   ]
  },
  {
   "title": "Parallelism",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubeml_job_parallelism{jobid=~\"$jobs\"}",
     "legendFormat": "{{jobid}}"
    }
   ]
  },
  {
   "title": "Epoch Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubeml_job_epoch_duration_seconds{jobid=~\"$jobs\"}",
     "legendFormat": "{{jobid}}"
    }
   ]
  }
 ]
}