apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: parameter-server-service-app
spec:
  selector:
    matchLabels:
      svc: parameter-server
  endpoints:
  - targetPort: 8080