apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: executor-service-app
  namespace: fission
spec:
  selector:
    matchLabels:
      svc: executor
  endpoints:
    - targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: router-service-app
  namespace: fission
spec:
  selector:
    matchLabels:
      svc: router
  endpoints:
    - targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: parameter-server-service-app
spec:
  selector:
    matchLabels:
      svc: parameter-server
  endpoints:
    - targetPort: 8080
      interval: 10s
