apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongodb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mongo.serviceName}}
spec:
  ports:
    - port: 27017
  type: {{.Values.mongo.serviceType}}
  selector:
    app: mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: redisai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisai
  template:
    metadata:
      labels:
        app: redisai
    spec:
      containers:
        - name: redisai
          image: redisai/redisai:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.redisai.serviceName}}
spec:
  ports:
    - port: 6379
  type:  {{.Values.redisai.serviceType}}
  selector:
    app: redisai