apiVersion: v1
kind: Namespace
metadata:
  name: "kubeml"
  labels:
    name: kubeml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: kubeml
  labels:
    svc: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: controller
  template:
    metadata:
      labels:
        svc: controller
    spec:
      containers:
        - name: controller
          image: diegostock12/kubeml:latest
          command: ["/kubeml"]
          args: ["--controllerPort", "10100"]
          readinessProbe:
            httpGet:
              path: "/health"
              port: 10100
            initialDelaySeconds: 1
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: "/health"
              port: 10100
            initialDelaySeconds: 35
            periodSeconds: 5
          ports:
            - containerPort: 10100
              name: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: kubeml
  labels:
    svc: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: scheduler
  template:
    metadata:
      labels:
        svc: scheduler
    spec:
      containers:
        - name: scheduler
          image: diegostock12/kubeml:latest
          command: ["/kubeml"]
          args: ["--schedulerPort", "10100"]
          readinessProbe:
            httpGet:
              path: "/health"
              port: 10100
            initialDelaySeconds: 1
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: "/health"
              port: 10100
            initialDelaySeconds: 35
            periodSeconds: 5
          ports:
            - containerPort: 10100
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parameter-server
  namespace: kubeml
  labels:
    svc: parameter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: parameter-server
  template:
    metadata:
      labels:
        svc: parameter-server
    spec:
      containers:
        - name: parameter-server
          image: diegostock12/kubeml:latest
          command: ["/kubeml"]
          args: ["--psPort", "10100"]
          readinessProbe:
            httpGet:
              path: "/health"
              port: 10100
            initialDelaySeconds: 1
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: "/health"
              port: 10100
            initialDelaySeconds: 35
            periodSeconds: 5
          ports:
            - containerPort: 10100
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: "controller"
  namespace: "kubeml"
spec:
  ports:
    - port: 80
      targetPort: 10100
  type: ClusterIP
  selector:
    svc: "controller"

---
apiVersion: v1
kind: Service
metadata:
  name: "scheduler"
  namespace: "kubeml"
spec:
  ports:
    - port: 80
      targetPort: 10100
  type: ClusterIP
  selector:
    svc: "scheduler"

---
apiVersion: v1
kind: Service
metadata:
  name: "parameter-server"
  namespace: "kubeml"
spec:
  ports:
    - port: 80
      targetPort: 10100
  type: ClusterIP
  selector:
    svc: "parameter-server"