apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisai-deployment
  labels:
    app: redisai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisai
  template:
    metadata:
      labels:
        app: redisai
    spec:
      containers:
        - name: redisai
          image: redisai/redisai:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: "redisai"
  namespace: "default"
spec:
  ports:
    - port: 6379
  type: LoadBalancer
  selector:
    app: "redisai"