
## TODO include here an option for standalone deployment or limit parallelism

## Service type for most components
serviceType: ClusterIP

## Controller is exposed in a LoadBalancer
controllerServiceType: LoadBalancer

## KubeML image
image: diegostock12/kubeml
kubemlVersion: "0.1.7"

## Storage service image
storageImage: diegostock12/storage-svc

## Namespace for the images
namespace: kubeml

## Configuration for the environment in which functions will run
## this is a fission CRD with a custom image and dependencies already installed
environment:
  defaultName: torch
  poolsize: 10
  cpuMin: 100m
  cpuMax: 1000m
  image: diegostock12/python-env
  imageVersion: "0.1.10"
  gracePeriod: 30
  version: 3



## Instructions for mongo deployment
mongo:
  serviceType: LoadBalancer
  serviceName: mongodb

## RedisAI config
redisai:
  serviceType: LoadBalancer
  serviceName: redisai





