name: Build python environment

on:
  push:
    branches:
    - master
#    - refactor-network
    - experiments


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: diegostock12/python-env
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ml/environment
        tags: "0.1.14-cuda"