name: kubeml
description: 'Build and publish the kubeml container'

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: diegostock12/kubeml
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ml
          tags: "latest"