name: KubeML CI

on:
  push:
    branches:
      - develop
      - k-avg
    schedule:
      - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

env:
  VERSION: "0.1.3-avg"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image with cache and publish
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: kubeml:$VERSION

#      - name: Build and Publish
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: diegostock12/kubeml
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          workdir: ml
#          tags: "0.1.3-avg"
#          cache: ${{ github.event_name != 'schedule' }}